version: '3'

services:
  mysql:
    hostname: mysql
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    # expose:
    #   - "3306"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=LSYMYSQL
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    networks: 
      - backend

  nginx:
    hostname: nginx
    image: nginx:latest
    # build: 
    #   context: ./nginx
    #   dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./web/staticfiles:/flask_static
    ports:
      - "5000:5000"
    depends_on:
      - web
    networks: 
      - backend

     

networks:
  backend: {}
